ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR   = /usr/share/arduino
ARDMK_PATH  = /usr/bin
#AVR_TOOLS_DIR=/usr

BOARD_TAG   = mega2560
ARDUINO_PORT = /dev/ttyACM*
ARDUINO_LIBS = TFT TouchScreen CmdMessenger

include $(ARDMK_DIR)/Arduino.mk 
